rootProject.name = "Live Football"
include(":app")
include(":core")
include(":design")
include(":league:api")
include(":league:domain")
include(":match:api")
include(":match:presentation")
include(":test_utils")
include(":match:domain")
