rootProject.name = "Live Football"
include(":android_test_utils")
include(":app")
include(":core")
include(":design")
include(":league")
include(":match:api")
include(":match:presentation")
include(":test_utils")
include(":match_details:api")
include(":match_details:presentation")
